// decks.js — pre-made starter vocabulary decks
// Each deck has: id, name, description, tag, cards[]
// cards[] items: { character, pinyin, meaning }

const STARTER_DECKS = [

  // ── HSK 1 ──────────────────────────────────────────────────────────────
  {
    id: "hsk1",
    name: "HSK 1",
    description: "150 essential words for the beginner exam",
    tag: "HSK 1",
    cards: [
      { character: "爱",    pinyin: "ài",          meaning: "love / like" },
      { character: "八",    pinyin: "bā",          meaning: "eight" },
      { character: "爸爸",  pinyin: "bàba",        meaning: "dad / father" },
      { character: "杯子",  pinyin: "bēizi",       meaning: "cup / glass" },
      { character: "北京",  pinyin: "Běijīng",     meaning: "Beijing" },
      { character: "本",    pinyin: "běn",         meaning: "(measure word for books)" },
      { character: "不客气",pinyin: "bú kèqi",     meaning: "you're welcome" },
      { character: "不",    pinyin: "bù",          meaning: "no / not" },
      { character: "菜",    pinyin: "cài",         meaning: "dish / vegetable" },
      { character: "茶",    pinyin: "chá",         meaning: "tea" },
      { character: "吃",    pinyin: "chī",         meaning: "eat" },
      { character: "出租车",pinyin: "chūzūchē",    meaning: "taxi" },
      { character: "打电话",pinyin: "dǎ diànhuà",  meaning: "make a phone call" },
      { character: "大",    pinyin: "dà",          meaning: "big / large" },
      { character: "的",    pinyin: "de",          meaning: "(possessive particle)" },
      { character: "点",    pinyin: "diǎn",        meaning: "o'clock / a bit" },
      { character: "电脑",  pinyin: "diànnǎo",     meaning: "computer" },
      { character: "电视",  pinyin: "diànshì",     meaning: "television" },
      { character: "电影",  pinyin: "diànyǐng",    meaning: "film / movie" },
      { character: "东西",  pinyin: "dōngxi",      meaning: "thing / stuff" },
      { character: "都",    pinyin: "dōu",         meaning: "all / both" },
      { character: "读",    pinyin: "dú",          meaning: "read" },
      { character: "对不起",pinyin: "duìbuqǐ",     meaning: "sorry" },
      { character: "多",    pinyin: "duō",         meaning: "many / much" },
      { character: "多少",  pinyin: "duōshǎo",     meaning: "how many / how much" },
      { character: "儿子",  pinyin: "érzi",        meaning: "son" },
      { character: "二",    pinyin: "èr",          meaning: "two" },
      { character: "饭馆",  pinyin: "fànguǎn",     meaning: "restaurant" },
      { character: "飞机",  pinyin: "fēijī",       meaning: "airplane" },
      { character: "分钟",  pinyin: "fēnzhōng",    meaning: "minute" },
      { character: "高兴",  pinyin: "gāoxìng",     meaning: "happy / glad" },
      { character: "个",    pinyin: "gè",          meaning: "(general measure word)" },
      { character: "工作",  pinyin: "gōngzuò",     meaning: "work / job" },
      { character: "狗",    pinyin: "gǒu",         meaning: "dog" },
      { character: "汉语",  pinyin: "Hànyǔ",       meaning: "Chinese language" },
      { character: "好",    pinyin: "hǎo",         meaning: "good / well" },
      { character: "喝",    pinyin: "hē",          meaning: "drink" },
      { character: "和",    pinyin: "hé",          meaning: "and / with" },
      { character: "很",    pinyin: "hěn",         meaning: "very" },
      { character: "后面",  pinyin: "hòumiàn",     meaning: "behind / at the back" },
      { character: "回",    pinyin: "huí",         meaning: "return / go back" },
      { character: "会",    pinyin: "huì",         meaning: "can / know how to" },
      { character: "几",    pinyin: "jǐ",          meaning: "how many (small number)" },
      { character: "家",    pinyin: "jiā",         meaning: "home / family" },
      { character: "叫",    pinyin: "jiào",        meaning: "be called / call" },
      { character: "今天",  pinyin: "jīntiān",     meaning: "today" },
      { character: "九",    pinyin: "jiǔ",         meaning: "nine" },
      { character: "开",    pinyin: "kāi",         meaning: "open / start / drive" },
      { character: "看",    pinyin: "kàn",         meaning: "look / watch / read" },
      { character: "看见",  pinyin: "kànjiàn",     meaning: "see / catch sight of" },
      { character: "块",    pinyin: "kuài",        meaning: "yuan (colloquial) / piece" },
      { character: "来",    pinyin: "lái",         meaning: "come" },
      { character: "老师",  pinyin: "lǎoshī",      meaning: "teacher" },
      { character: "了",    pinyin: "le",          meaning: "(completed action particle)" },
      { character: "冷",    pinyin: "lěng",        meaning: "cold" },
      { character: "里",    pinyin: "lǐ",          meaning: "inside" },
      { character: "六",    pinyin: "liù",         meaning: "six" },
      { character: "妈妈",  pinyin: "māma",        meaning: "mom / mother" },
      { character: "吗",    pinyin: "ma",          meaning: "(yes/no question particle)" },
      { character: "买",    pinyin: "mǎi",         meaning: "buy" },
      { character: "猫",    pinyin: "māo",         meaning: "cat" },
      { character: "没关系",pinyin: "méi guānxi",  meaning: "it's OK / never mind" },
      { character: "没有",  pinyin: "méiyǒu",      meaning: "don't have / there isn't" },
      { character: "们",    pinyin: "men",         meaning: "(plural suffix)" },
      { character: "哪",    pinyin: "nǎ",          meaning: "which" },
      { character: "那",    pinyin: "nà",          meaning: "that" },
      { character: "哪儿",  pinyin: "nǎr",         meaning: "where" },
      { character: "呢",    pinyin: "ne",          meaning: "(particle for follow-up question)" },
      { character: "你",    pinyin: "nǐ",          meaning: "you" },
      { character: "年",    pinyin: "nián",        meaning: "year" },
      { character: "女儿",  pinyin: "nǚ'ér",       meaning: "daughter" },
      { character: "朋友",  pinyin: "péngyou",     meaning: "friend" },
      { character: "漂亮",  pinyin: "piàoliang",   meaning: "beautiful / pretty" },
      { character: "苹果",  pinyin: "píngguǒ",     meaning: "apple" },
      { character: "七",    pinyin: "qī",          meaning: "seven" },
      { character: "前面",  pinyin: "qiánmiàn",    meaning: "in front / ahead" },
      { character: "钱",    pinyin: "qián",        meaning: "money" },
      { character: "请",    pinyin: "qǐng",        meaning: "please / invite" },
      { character: "去",    pinyin: "qù",          meaning: "go" },
      { character: "热",    pinyin: "rè",          meaning: "hot" },
      { character: "人",    pinyin: "rén",         meaning: "person / people" },
      { character: "认识",  pinyin: "rènshi",      meaning: "know / recognise (a person)" },
      { character: "日",    pinyin: "rì",          meaning: "day / sun" },
      { character: "三",    pinyin: "sān",         meaning: "three" },
      { character: "商店",  pinyin: "shāngdiàn",   meaning: "shop / store" },
      { character: "上",    pinyin: "shàng",       meaning: "above / on / last" },
      { character: "上午",  pinyin: "shàngwǔ",     meaning: "morning (before noon)" },
      { character: "少",    pinyin: "shǎo",        meaning: "few / little / less" },
      { character: "谁",    pinyin: "shéi",        meaning: "who" },
      { character: "什么",  pinyin: "shénme",      meaning: "what" },
      { character: "生日",  pinyin: "shēngrì",     meaning: "birthday" },
      { character: "时候",  pinyin: "shíhou",      meaning: "time / moment / when" },
      { character: "是",    pinyin: "shì",         meaning: "be (am / is / are)" },
      { character: "书",    pinyin: "shū",         meaning: "book" },
      { character: "水",    pinyin: "shuǐ",        meaning: "water" },
      { character: "水果",  pinyin: "shuǐguǒ",     meaning: "fruit" },
      { character: "睡觉",  pinyin: "shuìjiào",    meaning: "sleep" },
      { character: "说",    pinyin: "shuō",        meaning: "speak / say / talk" },
      { character: "四",    pinyin: "sì",          meaning: "four" },
      { character: "岁",    pinyin: "suì",         meaning: "years old" },
      { character: "他",    pinyin: "tā",          meaning: "he / him" },
      { character: "她",    pinyin: "tā",          meaning: "she / her" },
      { character: "太",    pinyin: "tài",         meaning: "too / extremely" },
      { character: "天气",  pinyin: "tiānqì",      meaning: "weather" },
      { character: "听",    pinyin: "tīng",        meaning: "listen / hear" },
      { character: "同学",  pinyin: "tóngxué",     meaning: "classmate" },
      { character: "喂",    pinyin: "wèi",         meaning: "hello (on phone) / hey" },
      { character: "我",    pinyin: "wǒ",          meaning: "I / me" },
      { character: "我们",  pinyin: "wǒmen",       meaning: "we / us" },
      { character: "五",    pinyin: "wǔ",          meaning: "five" },
      { character: "下",    pinyin: "xià",         meaning: "below / under / next" },
      { character: "下午",  pinyin: "xiàwǔ",       meaning: "afternoon" },
      { character: "下雨",  pinyin: "xià yǔ",      meaning: "to rain / it's raining" },
      { character: "先生",  pinyin: "xiānsheng",   meaning: "Mr. / sir / husband" },
      { character: "现在",  pinyin: "xiànzài",     meaning: "now" },
      { character: "想",    pinyin: "xiǎng",       meaning: "want to / think / miss" },
      { character: "小",    pinyin: "xiǎo",        meaning: "small / little" },
      { character: "小姐",  pinyin: "xiǎojiě",     meaning: "Miss / young woman" },
      { character: "笑",    pinyin: "xiào",        meaning: "laugh / smile" },
      { character: "些",    pinyin: "xiē",         meaning: "some / a few" },
      { character: "写",    pinyin: "xiě",         meaning: "write" },
      { character: "谢谢",  pinyin: "xièxie",      meaning: "thank you" },
      { character: "星期",  pinyin: "xīngqī",      meaning: "week" },
      { character: "学生",  pinyin: "xuésheng",    meaning: "student" },
      { character: "学习",  pinyin: "xuéxí",       meaning: "study / learn" },
      { character: "学校",  pinyin: "xuéxiào",     meaning: "school" },
      { character: "一",    pinyin: "yī",          meaning: "one" },
      { character: "一下",  pinyin: "yīxià",       meaning: "a moment / a bit" },
      { character: "衣服",  pinyin: "yīfu",        meaning: "clothes / clothing" },
      { character: "医生",  pinyin: "yīshēng",     meaning: "doctor" },
      { character: "医院",  pinyin: "yīyuàn",      meaning: "hospital" },
      { character: "椅子",  pinyin: "yǐzi",        meaning: "chair" },
      { character: "一起",  pinyin: "yīqǐ",        meaning: "together" },
      { character: "有",    pinyin: "yǒu",         meaning: "have / there is" },
      { character: "语言",  pinyin: "yǔyán",       meaning: "language" },
      { character: "再见",  pinyin: "zàijiàn",     meaning: "goodbye" },
      { character: "在",    pinyin: "zài",         meaning: "at / in / on" },
      { character: "怎么",  pinyin: "zěnme",       meaning: "how / why" },
      { character: "怎么样",pinyin: "zěnmeyàng",   meaning: "how is it? / what do you think?" },
      { character: "这",    pinyin: "zhè",         meaning: "this" },
      { character: "中国",  pinyin: "Zhōngguó",    meaning: "China" },
      { character: "中午",  pinyin: "zhōngwǔ",     meaning: "noon / midday" },
      { character: "住",    pinyin: "zhù",         meaning: "live / reside" },
      { character: "桌子",  pinyin: "zhuōzi",      meaning: "table / desk" },
      { character: "字",    pinyin: "zì",          meaning: "character / word" },
      { character: "昨天",  pinyin: "zuótiān",     meaning: "yesterday" },
      { character: "坐",    pinyin: "zuò",         meaning: "sit / take (a vehicle)" },
      { character: "做",    pinyin: "zuò",         meaning: "do / make" },
      { character: "零",    pinyin: "líng",        meaning: "zero" },
      { character: "号",    pinyin: "hào",         meaning: "number / date (of month)" },
    ]
  },

  // ── HSK 2 ──────────────────────────────────────────────────────────────
  {
    id: "hsk2",
    name: "HSK 2",
    description: "150 words for the elementary exam",
    tag: "HSK 2",
    cards: [
      { character: "吧",    pinyin: "ba",          meaning: "(suggestion / assumption particle)" },
      { character: "白",    pinyin: "bái",         meaning: "white" },
      { character: "百",    pinyin: "bǎi",         meaning: "hundred" },
      { character: "帮助",  pinyin: "bāngzhù",     meaning: "help / assist" },
      { character: "报纸",  pinyin: "bàozhǐ",      meaning: "newspaper" },
      { character: "比",    pinyin: "bǐ",          meaning: "compare / than" },
      { character: "别",    pinyin: "bié",         meaning: "don't / other" },
      { character: "不好意思",pinyin: "bù hǎoyìsi", meaning: "embarrassed / excuse me" },
      { character: "才",    pinyin: "cái",         meaning: "just / only / not until" },
      { character: "从",    pinyin: "cóng",        meaning: "from / since" },
      { character: "错",    pinyin: "cuò",         meaning: "wrong / mistake" },
      { character: "打篮球",pinyin: "dǎ lánqiú",   meaning: "play basketball" },
      { character: "大家",  pinyin: "dàjiā",       meaning: "everyone / everybody" },
      { character: "到",    pinyin: "dào",         meaning: "arrive / reach / to" },
      { character: "第一",  pinyin: "dì yī",       meaning: "first / number one" },
      { character: "弟弟",  pinyin: "dìdi",        meaning: "younger brother" },
      { character: "懂",    pinyin: "dǒng",        meaning: "understand" },
      { character: "对",    pinyin: "duì",         meaning: "correct / right / toward" },
      { character: "房间",  pinyin: "fángjiān",    meaning: "room" },
      { character: "放",    pinyin: "fàng",        meaning: "put / place / let go" },
      { character: "非常",  pinyin: "fēicháng",    meaning: "very / extremely" },
      { character: "附近",  pinyin: "fùjìn",       meaning: "nearby / vicinity" },
      { character: "复习",  pinyin: "fùxí",        meaning: "review / revise" },
      { character: "告诉",  pinyin: "gàosu",       meaning: "tell / inform" },
      { character: "哥哥",  pinyin: "gēge",        meaning: "older brother" },
      { character: "给",    pinyin: "gěi",         meaning: "give / for" },
      { character: "公共汽车",pinyin: "gōnggòng qìchē", meaning: "public bus" },
      { character: "公斤",  pinyin: "gōngjīn",     meaning: "kilogram" },
      { character: "公里",  pinyin: "gōnglǐ",      meaning: "kilometer" },
      { character: "公司",  pinyin: "gōngsī",      meaning: "company / firm" },
      { character: "贵",    pinyin: "guì",         meaning: "expensive / honourable" },
      { character: "过",    pinyin: "guò",         meaning: "pass / spend (time)" },
      { character: "还",    pinyin: "hái",         meaning: "still / also / in addition" },
      { character: "孩子",  pinyin: "háizi",       meaning: "child / children" },
      { character: "好吃",  pinyin: "hǎochī",      meaning: "delicious / tasty" },
      { character: "黑",    pinyin: "hēi",         meaning: "black" },
      { character: "红",    pinyin: "hóng",        meaning: "red" },
      { character: "火车站",pinyin: "huǒchē zhàn", meaning: "train station" },
      { character: "机场",  pinyin: "jīchǎng",     meaning: "airport" },
      { character: "鸡蛋",  pinyin: "jīdàn",       meaning: "egg" },
      { character: "件",    pinyin: "jiàn",        meaning: "(measure word for items/clothes)" },
      { character: "教室",  pinyin: "jiàoshì",     meaning: "classroom" },
      { character: "结束",  pinyin: "jiéshù",      meaning: "end / finish" },
      { character: "姐姐",  pinyin: "jiějie",      meaning: "older sister" },
      { character: "进",    pinyin: "jìn",         meaning: "enter / go in" },
      { character: "近",    pinyin: "jìn",         meaning: "near / close" },
      { character: "就",    pinyin: "jiù",         meaning: "then / just / only" },
      { character: "可能",  pinyin: "kěnéng",      meaning: "maybe / possible" },
      { character: "可以",  pinyin: "kěyǐ",        meaning: "can / may" },
      { character: "快",    pinyin: "kuài",        meaning: "fast / quick" },
      { character: "乐",    pinyin: "lè",          meaning: "happy / joyful" },
      { character: "离",    pinyin: "lí",          meaning: "away from / distance" },
      { character: "两",    pinyin: "liǎng",       meaning: "two (before measure word)" },
      { character: "楼",    pinyin: "lóu",         meaning: "building / floor / storey" },
      { character: "路",    pinyin: "lù",          meaning: "road / route" },
      { character: "旅游",  pinyin: "lǚyóu",       meaning: "travel / tourism" },
      { character: "卖",    pinyin: "mài",         meaning: "sell" },
      { character: "慢",    pinyin: "màn",         meaning: "slow" },
      { character: "忙",    pinyin: "máng",        meaning: "busy" },
      { character: "每",    pinyin: "měi",         meaning: "every / each" },
      { character: "妹妹",  pinyin: "mèimei",      meaning: "younger sister" },
      { character: "面条",  pinyin: "miàntiáo",    meaning: "noodles" },
      { character: "明白",  pinyin: "míngbai",     meaning: "understand / clear" },
      { character: "明年",  pinyin: "míngnián",    meaning: "next year" },
      { character: "明天",  pinyin: "míngtiān",    meaning: "tomorrow" },
      { character: "男",    pinyin: "nán",         meaning: "male / man" },
      { character: "您",    pinyin: "nín",         meaning: "you (polite form)" },
      { character: "牛奶",  pinyin: "niúnǎi",      meaning: "milk" },
      { character: "女",    pinyin: "nǚ",          meaning: "female / woman" },
      { character: "跑步",  pinyin: "pǎobù",       meaning: "run / jog" },
      { character: "便宜",  pinyin: "piányí",      meaning: "cheap / inexpensive" },
      { character: "票",    pinyin: "piào",        meaning: "ticket" },
      { character: "妻子",  pinyin: "qīzi",        meaning: "wife" },
      { character: "起床",  pinyin: "qǐchuáng",    meaning: "get up / get out of bed" },
      { character: "骑",    pinyin: "qí",          meaning: "ride (a bike or horse)" },
      { character: "铅笔",  pinyin: "qiānbǐ",      meaning: "pencil" },
      { character: "千",    pinyin: "qiān",        meaning: "thousand" },
      { character: "让",    pinyin: "ràng",        meaning: "let / allow / make" },
      { character: "日记",  pinyin: "rìjì",        meaning: "diary" },
      { character: "如果",  pinyin: "rúguǒ",       meaning: "if / in case" },
      { character: "身体",  pinyin: "shēntǐ",      meaning: "body / health" },
      { character: "生病",  pinyin: "shēngbìng",   meaning: "be sick / fall ill" },
      { character: "生活",  pinyin: "shēnghuó",    meaning: "life / live" },
      { character: "声音",  pinyin: "shēngyīn",    meaning: "sound / voice" },
      { character: "事情",  pinyin: "shìqing",     meaning: "thing / matter / affair" },
      { character: "手机",  pinyin: "shǒujī",      meaning: "mobile phone / cell phone" },
      { character: "瘦",    pinyin: "shòu",        meaning: "thin / slim" },
      { character: "送",    pinyin: "sòng",        meaning: "send / give as gift / see off" },
      { character: "宿舍",  pinyin: "sùshè",       meaning: "dormitory" },
      { character: "虽然",  pinyin: "suīrán",      meaning: "although / even though" },
      { character: "它",    pinyin: "tā",          meaning: "it" },
      { character: "踢足球",pinyin: "tī zúqiú",    meaning: "play soccer" },
      { character: "疼",    pinyin: "téng",        meaning: "ache / hurt" },
      { character: "甜",    pinyin: "tián",        meaning: "sweet" },
      { character: "同事",  pinyin: "tóngshì",     meaning: "colleague" },
      { character: "推",    pinyin: "tuī",         meaning: "push" },
      { character: "完",    pinyin: "wán",         meaning: "finish / complete" },
      { character: "外面",  pinyin: "wàimiàn",     meaning: "outside" },
      { character: "忘",    pinyin: "wàng",        meaning: "forget" },
      { character: "为什么",pinyin: "wèishénme",   meaning: "why" },
      { character: "问",    pinyin: "wèn",         meaning: "ask" },
      { character: "问题",  pinyin: "wèntí",       meaning: "question / problem" },
      { character: "希望",  pinyin: "xīwàng",      meaning: "hope / wish" },
      { character: "洗",    pinyin: "xǐ",          meaning: "wash" },
      { character: "向",    pinyin: "xiàng",       meaning: "toward / in the direction of" },
      { character: "小时",  pinyin: "xiǎoshí",     meaning: "hour" },
      { character: "新",    pinyin: "xīn",         meaning: "new" },
      { character: "姓",    pinyin: "xìng",        meaning: "surname / be surnamed" },
      { character: "休息",  pinyin: "xiūxi",       meaning: "rest / take a break" },
      { character: "颜色",  pinyin: "yánsè",       meaning: "color" },
      { character: "眼睛",  pinyin: "yǎnjing",     meaning: "eyes" },
      { character: "要",    pinyin: "yào",         meaning: "want / need / will" },
      { character: "也",    pinyin: "yě",          meaning: "also / too / either" },
      { character: "以为",  pinyin: "yǐwéi",       meaning: "think / believe (mistakenly)" },
      { character: "因为",  pinyin: "yīnwèi",      meaning: "because" },
      { character: "意思",  pinyin: "yìsi",        meaning: "meaning / idea" },
      { character: "音乐",  pinyin: "yīnyuè",      meaning: "music" },
      { character: "游泳",  pinyin: "yóuyǒng",     meaning: "swim" },
      { character: "右",    pinyin: "yòu",         meaning: "right (direction)" },
      { character: "又",    pinyin: "yòu",         meaning: "again / also" },
      { character: "鱼",    pinyin: "yú",          meaning: "fish" },
      { character: "运动",  pinyin: "yùndòng",     meaning: "exercise / sport" },
      { character: "再",    pinyin: "zài",         meaning: "again" },
      { character: "早上",  pinyin: "zǎoshang",    meaning: "morning (early)" },
      { character: "丈夫",  pinyin: "zhàngfu",     meaning: "husband" },
      { character: "找",    pinyin: "zhǎo",        meaning: "look for / find" },
      { character: "着",    pinyin: "zhe",         meaning: "(continuous action particle)" },
      { character: "真",    pinyin: "zhēn",        meaning: "true / real / really" },
      { character: "正在",  pinyin: "zhèngzài",    meaning: "right now / in the process of" },
      { character: "知道",  pinyin: "zhīdào",      meaning: "know / be aware of" },
      { character: "准备",  pinyin: "zhǔnbèi",     meaning: "prepare / get ready" },
      { character: "走",    pinyin: "zǒu",         meaning: "walk / go" },
      { character: "最",    pinyin: "zuì",         meaning: "most (superlative)" },
      { character: "左",    pinyin: "zuǒ",         meaning: "left (direction)" },
      { character: "作业",  pinyin: "zuòyè",       meaning: "homework / assignment" },
      { character: "班",    pinyin: "bān",         meaning: "class / shift" },
      { character: "长",    pinyin: "cháng",       meaning: "long" },
      { character: "唱歌",  pinyin: "chàng gē",    meaning: "sing (a song)" },
      { character: "出",    pinyin: "chū",         meaning: "go out / exit" },
      { character: "除了",  pinyin: "chúle",       meaning: "except / apart from" },
      { character: "大学",  pinyin: "dàxué",       meaning: "university" },
      { character: "等",    pinyin: "děng",        meaning: "wait" },
      { character: "地方",  pinyin: "dìfang",      meaning: "place / area" },
      { character: "地铁",  pinyin: "dìtiě",       meaning: "subway / metro" },
      { character: "动物",  pinyin: "dòngwù",      meaning: "animal" },
      { character: "短",    pinyin: "duǎn",        meaning: "short" },
      { character: "发现",  pinyin: "fāxiàn",      meaning: "discover / find" },
      { character: "方便",  pinyin: "fāngbiàn",    meaning: "convenient" },
    ]
  },

  // ── ANIMALS ────────────────────────────────────────────────────────────
  {
    id: "animals",
    name: "Animals",
    description: "Common animals in Chinese",
    tag: "Animals",
    cards: [
      { character: "狗",    pinyin: "gǒu",       meaning: "dog" },
      { character: "猫",    pinyin: "māo",       meaning: "cat" },
      { character: "鸟",    pinyin: "niǎo",      meaning: "bird" },
      { character: "鱼",    pinyin: "yú",        meaning: "fish" },
      { character: "马",    pinyin: "mǎ",        meaning: "horse" },
      { character: "牛",    pinyin: "niú",       meaning: "cow / ox" },
      { character: "猪",    pinyin: "zhū",       meaning: "pig" },
      { character: "羊",    pinyin: "yáng",      meaning: "sheep / goat" },
      { character: "鸡",    pinyin: "jī",        meaning: "chicken" },
      { character: "兔子",  pinyin: "tùzi",      meaning: "rabbit" },
      { character: "老虎",  pinyin: "lǎohǔ",     meaning: "tiger" },
      { character: "熊猫",  pinyin: "xióngmāo",  meaning: "panda" },
      { character: "大象",  pinyin: "dàxiàng",   meaning: "elephant" },
      { character: "猴子",  pinyin: "hóuzi",     meaning: "monkey" },
      { character: "蛇",    pinyin: "shé",       meaning: "snake" },
      { character: "狮子",  pinyin: "shīzi",     meaning: "lion" },
      { character: "熊",    pinyin: "xióng",     meaning: "bear" },
      { character: "青蛙",  pinyin: "qīngwā",    meaning: "frog" },
      { character: "鸭子",  pinyin: "yāzi",      meaning: "duck" },
      { character: "蝴蝶",  pinyin: "húdié",     meaning: "butterfly" },
    ]
  },

  // ── FRUITS ─────────────────────────────────────────────────────────────
  {
    id: "fruits",
    name: "Fruits",
    description: "Common fruits in Chinese",
    tag: "Fruits",
    cards: [
      { character: "苹果",  pinyin: "píngguǒ",   meaning: "apple" },
      { character: "香蕉",  pinyin: "xiāngjiāo", meaning: "banana" },
      { character: "橙子",  pinyin: "chéngzi",   meaning: "orange" },
      { character: "葡萄",  pinyin: "pútao",     meaning: "grape" },
      { character: "西瓜",  pinyin: "xīguā",     meaning: "watermelon" },
      { character: "草莓",  pinyin: "cǎoméi",    meaning: "strawberry" },
      { character: "芒果",  pinyin: "mángguǒ",   meaning: "mango" },
      { character: "梨",    pinyin: "lí",        meaning: "pear" },
      { character: "桃子",  pinyin: "táozi",     meaning: "peach" },
      { character: "樱桃",  pinyin: "yīngtáo",   meaning: "cherry" },
      { character: "柠檬",  pinyin: "níngméng",  meaning: "lemon" },
      { character: "菠萝",  pinyin: "bōluó",     meaning: "pineapple" },
      { character: "猕猴桃",pinyin: "míhóutáo",  meaning: "kiwi fruit" },
      { character: "椰子",  pinyin: "yēzi",      meaning: "coconut" },
      { character: "哈密瓜",pinyin: "hāmìguā",   meaning: "cantaloupe / honeydew melon" },
      { character: "荔枝",  pinyin: "lìzhī",     meaning: "lychee" },
      { character: "柚子",  pinyin: "yòuzi",     meaning: "pomelo" },
      { character: "李子",  pinyin: "lǐzi",      meaning: "plum" },
      { character: "蓝莓",  pinyin: "lánméi",    meaning: "blueberry" },
      { character: "木瓜",  pinyin: "mùguā",     meaning: "papaya" },
    ]
  },

  // ── VEGETABLES ─────────────────────────────────────────────────────────
  {
    id: "vegetables",
    name: "Vegetables",
    description: "Common vegetables in Chinese",
    tag: "Vegetables",
    cards: [
      { character: "胡萝卜",pinyin: "húluóbo",   meaning: "carrot" },
      { character: "土豆",  pinyin: "tǔdòu",     meaning: "potato" },
      { character: "洋葱",  pinyin: "yángcōng",  meaning: "onion" },
      { character: "大蒜",  pinyin: "dàsuàn",    meaning: "garlic" },
      { character: "黄瓜",  pinyin: "huángguā",  meaning: "cucumber" },
      { character: "西红柿",pinyin: "xīhóngshì", meaning: "tomato" },
      { character: "茄子",  pinyin: "qiézi",     meaning: "eggplant / aubergine" },
      { character: "白菜",  pinyin: "báicài",    meaning: "cabbage / Chinese cabbage" },
      { character: "西兰花",pinyin: "xīlánhuā",  meaning: "broccoli" },
      { character: "菠菜",  pinyin: "bōcài",     meaning: "spinach" },
      { character: "青椒",  pinyin: "qīngjiāo",  meaning: "green pepper" },
      { character: "玉米",  pinyin: "yùmǐ",      meaning: "corn / maize" },
      { character: "蘑菇",  pinyin: "mógu",      meaning: "mushroom" },
      { character: "芹菜",  pinyin: "qíncài",    meaning: "celery" },
      { character: "南瓜",  pinyin: "nánguā",    meaning: "pumpkin" },
      { character: "豆角",  pinyin: "dòujiǎo",   meaning: "green beans / string beans" },
      { character: "萝卜",  pinyin: "luóbo",     meaning: "radish / turnip" },
      { character: "生菜",  pinyin: "shēngcài",  meaning: "lettuce" },
      { character: "豌豆",  pinyin: "wāndòu",    meaning: "pea" },
      { character: "韭菜",  pinyin: "jiǔcài",    meaning: "chives / Chinese leek" },
    ]
  },

  // ── FOOD & DRINKS ──────────────────────────────────────────────────────
  {
    id: "food",
    name: "Food & Drinks",
    description: "Common food and drink in Chinese",
    tag: "Food",
    cards: [
      { character: "米饭",  pinyin: "mǐfàn",     meaning: "cooked rice" },
      { character: "面包",  pinyin: "miànbāo",   meaning: "bread" },
      { character: "肉",    pinyin: "ròu",       meaning: "meat" },
      { character: "鸡肉",  pinyin: "jīròu",     meaning: "chicken (meat)" },
      { character: "猪肉",  pinyin: "zhūròu",    meaning: "pork" },
      { character: "牛肉",  pinyin: "niúròu",    meaning: "beef" },
      { character: "豆腐",  pinyin: "dòufu",     meaning: "tofu" },
      { character: "汤",    pinyin: "tāng",      meaning: "soup" },
      { character: "果汁",  pinyin: "guǒzhī",    meaning: "fruit juice" },
      { character: "啤酒",  pinyin: "píjiǔ",     meaning: "beer" },
      { character: "咖啡",  pinyin: "kāfēi",     meaning: "coffee" },
      { character: "饺子",  pinyin: "jiǎozi",    meaning: "dumpling (boiled)" },
      { character: "包子",  pinyin: "bāozi",     meaning: "steamed stuffed bun" },
      { character: "火锅",  pinyin: "huǒguō",    meaning: "hot pot" },
      { character: "炒饭",  pinyin: "chǎofàn",   meaning: "fried rice" },
      { character: "粥",    pinyin: "zhōu",      meaning: "congee / rice porridge" },
      { character: "糖",    pinyin: "táng",      meaning: "sugar / candy / sweets" },
      { character: "盐",    pinyin: "yán",       meaning: "salt" },
      { character: "油",    pinyin: "yóu",       meaning: "oil" },
      { character: "醋",    pinyin: "cù",        meaning: "vinegar" },
    ]
  },

  // ── BODY PARTS ─────────────────────────────────────────────────────────
  {
    id: "body",
    name: "Body Parts",
    description: "Parts of the human body",
    tag: "Body",
    cards: [
      { character: "头",    pinyin: "tóu",       meaning: "head" },
      { character: "脸",    pinyin: "liǎn",      meaning: "face" },
      { character: "耳朵",  pinyin: "ěrduo",     meaning: "ear" },
      { character: "鼻子",  pinyin: "bízi",      meaning: "nose" },
      { character: "嘴巴",  pinyin: "zuǐba",     meaning: "mouth" },
      { character: "手",    pinyin: "shǒu",      meaning: "hand" },
      { character: "手臂",  pinyin: "shǒubì",    meaning: "arm" },
      { character: "腿",    pinyin: "tuǐ",       meaning: "leg" },
      { character: "脚",    pinyin: "jiǎo",      meaning: "foot" },
      { character: "手指",  pinyin: "shǒuzhǐ",   meaning: "finger" },
      { character: "肩膀",  pinyin: "jiānbǎng",  meaning: "shoulder" },
      { character: "脖子",  pinyin: "bózi",      meaning: "neck" },
      { character: "胸",    pinyin: "xiōng",     meaning: "chest" },
      { character: "肚子",  pinyin: "dùzi",      meaning: "stomach / belly" },
      { character: "背",    pinyin: "bèi",       meaning: "back (of body)" },
      { character: "头发",  pinyin: "tóufa",     meaning: "hair" },
      { character: "牙齿",  pinyin: "yáchǐ",     meaning: "teeth" },
      { character: "舌头",  pinyin: "shétou",    meaning: "tongue" },
      { character: "嘴唇",  pinyin: "zuǐchún",   meaning: "lips" },
      { character: "膝盖",  pinyin: "xīgài",     meaning: "knee" },
    ]
  },

  // ── FAMILY ─────────────────────────────────────────────────────────────
  {
    id: "family",
    name: "Family",
    description: "Family members and relationships",
    tag: "Family",
    cards: [
      { character: "爸爸",  pinyin: "bàba",      meaning: "father / dad" },
      { character: "妈妈",  pinyin: "māma",      meaning: "mother / mom" },
      { character: "哥哥",  pinyin: "gēge",      meaning: "older brother" },
      { character: "姐姐",  pinyin: "jiějie",    meaning: "older sister" },
      { character: "弟弟",  pinyin: "dìdi",      meaning: "younger brother" },
      { character: "妹妹",  pinyin: "mèimei",    meaning: "younger sister" },
      { character: "爷爷",  pinyin: "yéye",      meaning: "paternal grandfather" },
      { character: "奶奶",  pinyin: "nǎinai",    meaning: "paternal grandmother" },
      { character: "外公",  pinyin: "wàigōng",   meaning: "maternal grandfather" },
      { character: "外婆",  pinyin: "wàipó",     meaning: "maternal grandmother" },
      { character: "儿子",  pinyin: "érzi",      meaning: "son" },
      { character: "女儿",  pinyin: "nǚ'ér",     meaning: "daughter" },
      { character: "丈夫",  pinyin: "zhàngfu",   meaning: "husband" },
      { character: "妻子",  pinyin: "qīzi",      meaning: "wife" },
      { character: "孩子",  pinyin: "háizi",     meaning: "child" },
      { character: "叔叔",  pinyin: "shūshu",    meaning: "uncle (father's younger brother)" },
      { character: "阿姨",  pinyin: "āyí",       meaning: "aunt (mother's sister)" },
      { character: "舅舅",  pinyin: "jiùjiu",    meaning: "uncle (mother's brother)" },
      { character: "表哥",  pinyin: "biǎogē",    meaning: "older male cousin" },
      { character: "家人",  pinyin: "jiārén",    meaning: "family members" },
    ]
  },

  // ── COLORS ─────────────────────────────────────────────────────────────
  {
    id: "colors",
    name: "Colors",
    description: "Colors and shades in Chinese",
    tag: "Colors",
    cards: [
      { character: "红色",  pinyin: "hóngsè",    meaning: "red" },
      { character: "蓝色",  pinyin: "lánsè",     meaning: "blue" },
      { character: "黄色",  pinyin: "huángsè",   meaning: "yellow" },
      { character: "绿色",  pinyin: "lǜsè",      meaning: "green" },
      { character: "黑色",  pinyin: "hēisè",     meaning: "black" },
      { character: "白色",  pinyin: "báisè",     meaning: "white" },
      { character: "紫色",  pinyin: "zǐsè",      meaning: "purple" },
      { character: "橙色",  pinyin: "chéngsè",   meaning: "orange (color)" },
      { character: "粉色",  pinyin: "fěnsè",     meaning: "pink" },
      { character: "灰色",  pinyin: "huīsè",     meaning: "grey / gray" },
      { character: "棕色",  pinyin: "zōngsè",    meaning: "brown" },
      { character: "金色",  pinyin: "jīnsè",     meaning: "gold / golden" },
      { character: "银色",  pinyin: "yínsè",     meaning: "silver" },
      { character: "浅蓝",  pinyin: "qiǎnlán",   meaning: "light blue" },
      { character: "深红",  pinyin: "shēnhóng",  meaning: "dark red / crimson" },
      { character: "颜色",  pinyin: "yánsè",     meaning: "color" },
      { character: "彩虹",  pinyin: "cǎihóng",   meaning: "rainbow" },
      { character: "亮",    pinyin: "liàng",     meaning: "bright / shining" },
      { character: "暗",    pinyin: "àn",        meaning: "dark / dim" },
      { character: "透明",  pinyin: "tòumíng",   meaning: "transparent / clear" },
    ]
  },

  // ── NUMBERS & TIME ─────────────────────────────────────────────────────
  {
    id: "time",
    name: "Numbers & Time",
    description: "Numbers, dates, and time expressions",
    tag: "Time",
    cards: [
      { character: "十",    pinyin: "shí",       meaning: "ten" },
      { character: "百",    pinyin: "bǎi",       meaning: "hundred" },
      { character: "千",    pinyin: "qiān",      meaning: "thousand" },
      { character: "万",    pinyin: "wàn",       meaning: "ten thousand" },
      { character: "月",    pinyin: "yuè",       meaning: "month / moon" },
      { character: "秒",    pinyin: "miǎo",      meaning: "second (time unit)" },
      { character: "晚上",  pinyin: "wǎnshang",  meaning: "evening / night" },
      { character: "前年",  pinyin: "qiánnián",  meaning: "the year before last" },
      { character: "后天",  pinyin: "hòutiān",   meaning: "the day after tomorrow" },
      { character: "每天",  pinyin: "měitiān",   meaning: "every day" },
      { character: "半",    pinyin: "bàn",       meaning: "half" },
      { character: "刚才",  pinyin: "gāngcái",   meaning: "just now / a moment ago" },
      { character: "以前",  pinyin: "yǐqián",    meaning: "before / in the past" },
      { character: "以后",  pinyin: "yǐhòu",     meaning: "after / in the future" },
      { character: "经常",  pinyin: "jīngcháng", meaning: "often / frequently" },
      { character: "有时候",pinyin: "yǒu shíhou",meaning: "sometimes" },
      { character: "马上",  pinyin: "mǎshàng",   meaning: "right away / immediately" },
      { character: "已经",  pinyin: "yǐjīng",    meaning: "already" },
      { character: "还是",  pinyin: "háishi",    meaning: "or / still / had better" },
      { character: "快要",  pinyin: "kuàiyào",   meaning: "about to / soon" },
    ]
  },

  // ── TRANSPORT ──────────────────────────────────────────────────────────
  {
    id: "transport",
    name: "Transport",
    description: "Getting around — vehicles and travel",
    tag: "Transport",
    cards: [
      { character: "汽车",  pinyin: "qìchē",     meaning: "car / automobile" },
      { character: "火车",  pinyin: "huǒchē",    meaning: "train" },
      { character: "船",    pinyin: "chuán",     meaning: "ship / boat" },
      { character: "摩托车",pinyin: "mótuōchē",  meaning: "motorcycle" },
      { character: "自行车",pinyin: "zìxíngchē", meaning: "bicycle" },
      { character: "走路",  pinyin: "zǒu lù",    meaning: "walk" },
      { character: "车站",  pinyin: "chēzhàn",   meaning: "bus / train stop" },
      { character: "司机",  pinyin: "sījī",      meaning: "driver" },
      { character: "速度",  pinyin: "sùdù",      meaning: "speed" },
      { character: "交通",  pinyin: "jiāotōng",  meaning: "traffic / transportation" },
      { character: "停车",  pinyin: "tíng chē",  meaning: "park a car" },
      { character: "桥",    pinyin: "qiáo",      meaning: "bridge" },
      { character: "地图",  pinyin: "dìtú",      meaning: "map" },
      { character: "行李",  pinyin: "xíngli",    meaning: "luggage / baggage" },
      { character: "护照",  pinyin: "hùzhào",    meaning: "passport" },
      { character: "换乘",  pinyin: "huànchéng", meaning: "transfer / change (transit)" },
      { character: "堵车",  pinyin: "dǔ chē",    meaning: "traffic jam" },
      { character: "出发",  pinyin: "chūfā",     meaning: "set off / depart" },
      { character: "到达",  pinyin: "dàodá",     meaning: "arrive / reach (destination)" },
      { character: "方向",  pinyin: "fāngxiàng", meaning: "direction" },
    ]
  },

  // ── WEATHER ────────────────────────────────────────────────────────────
  {
    id: "weather",
    name: "Weather",
    description: "Weather conditions and seasons",
    tag: "Weather",
    cards: [
      { character: "晴天",  pinyin: "qíngtiān",  meaning: "sunny day / clear sky" },
      { character: "多云",  pinyin: "duō yún",   meaning: "cloudy" },
      { character: "下雪",  pinyin: "xià xuě",   meaning: "snow / it's snowing" },
      { character: "刮风",  pinyin: "guā fēng",  meaning: "windy / wind is blowing" },
      { character: "大雾",  pinyin: "dà wù",     meaning: "heavy fog" },
      { character: "暖和",  pinyin: "nuǎnhuo",   meaning: "warm" },
      { character: "凉快",  pinyin: "liángkuài", meaning: "cool and refreshing" },
      { character: "温度",  pinyin: "wēndù",     meaning: "temperature" },
      { character: "天气预报",pinyin: "tiānqì yùbào", meaning: "weather forecast" },
      { character: "台风",  pinyin: "táifēng",   meaning: "typhoon" },
      { character: "雷",    pinyin: "léi",       meaning: "thunder" },
      { character: "闪电",  pinyin: "shǎndiàn",  meaning: "lightning" },
      { character: "湿度",  pinyin: "shīdù",     meaning: "humidity" },
      { character: "季节",  pinyin: "jìjié",     meaning: "season" },
      { character: "春天",  pinyin: "chūntiān",  meaning: "spring" },
      { character: "夏天",  pinyin: "xiàtiān",   meaning: "summer" },
      { character: "秋天",  pinyin: "qiūtiān",   meaning: "autumn / fall" },
      { character: "冬天",  pinyin: "dōngtiān",  meaning: "winter" },
      { character: "风",    pinyin: "fēng",      meaning: "wind" },
      { character: "雨",    pinyin: "yǔ",        meaning: "rain" },
    ]
  },

  // ── CLOTHES ────────────────────────────────────────────────────────────
  {
    id: "clothes",
    name: "Clothes",
    description: "Clothing and accessories",
    tag: "Clothes",
    cards: [
      { character: "衬衫",  pinyin: "chènshān",  meaning: "shirt" },
      { character: "裤子",  pinyin: "kùzi",      meaning: "pants / trousers" },
      { character: "裙子",  pinyin: "qúnzi",     meaning: "skirt" },
      { character: "连衣裙",pinyin: "liányīqún",  meaning: "dress (one-piece)" },
      { character: "夹克",  pinyin: "jiākè",     meaning: "jacket" },
      { character: "大衣",  pinyin: "dàyī",      meaning: "overcoat" },
      { character: "鞋子",  pinyin: "xiézi",     meaning: "shoes" },
      { character: "袜子",  pinyin: "wàzi",      meaning: "socks" },
      { character: "帽子",  pinyin: "màozi",     meaning: "hat / cap" },
      { character: "围巾",  pinyin: "wéijīn",    meaning: "scarf" },
      { character: "手套",  pinyin: "shǒutào",   meaning: "gloves" },
      { character: "内衣",  pinyin: "nèiyī",     meaning: "underwear" },
      { character: "毛衣",  pinyin: "máoyī",     meaning: "sweater / jumper" },
      { character: "短裤",  pinyin: "duǎnkù",    meaning: "shorts" },
      { character: "靴子",  pinyin: "xuēzi",     meaning: "boots" },
      { character: "凉鞋",  pinyin: "liángxié",  meaning: "sandals" },
      { character: "皮带",  pinyin: "pídài",     meaning: "belt" },
      { character: "领带",  pinyin: "lǐngdài",   meaning: "tie / necktie" },
      { character: "睡衣",  pinyin: "shuìyī",    meaning: "pajamas" },
      { character: "泳衣",  pinyin: "yǒngyī",    meaning: "swimsuit" },
    ]
  },

  // ── HOME OBJECTS ───────────────────────────────────────────────────────
  {
    id: "home",
    name: "Home Objects",
    description: "Furniture and things around the house",
    tag: "Home",
    cards: [
      { character: "床",    pinyin: "chuáng",    meaning: "bed" },
      { character: "沙发",  pinyin: "shāfā",     meaning: "sofa / couch" },
      { character: "灯",    pinyin: "dēng",      meaning: "lamp / light" },
      { character: "门",    pinyin: "mén",       meaning: "door / gate" },
      { character: "窗户",  pinyin: "chuānghù",  meaning: "window" },
      { character: "地板",  pinyin: "dìbǎn",     meaning: "floor" },
      { character: "墙",    pinyin: "qiáng",     meaning: "wall" },
      { character: "厨房",  pinyin: "chúfáng",   meaning: "kitchen" },
      { character: "卫生间",pinyin: "wèishēngjiān", meaning: "bathroom / restroom" },
      { character: "客厅",  pinyin: "kètīng",    meaning: "living room" },
      { character: "卧室",  pinyin: "wòshì",     meaning: "bedroom" },
      { character: "冰箱",  pinyin: "bīngxiāng", meaning: "refrigerator / fridge" },
      { character: "洗衣机",pinyin: "xǐyījī",    meaning: "washing machine" },
      { character: "空调",  pinyin: "kōngtiáo",  meaning: "air conditioner" },
      { character: "风扇",  pinyin: "fēngshàn",  meaning: "electric fan" },
      { character: "钟",    pinyin: "zhōng",     meaning: "clock" },
      { character: "书架",  pinyin: "shūjià",    meaning: "bookshelf" },
      { character: "花瓶",  pinyin: "huāpíng",   meaning: "vase" },
      { character: "垃圾桶",pinyin: "lājītǒng",  meaning: "rubbish bin / trash can" },
      { character: "微波炉",pinyin: "wēibōlú",   meaning: "microwave oven" },
    ]
  },

  // ── BATHROOM ───────────────────────────────────────────────────────────
  {
    id: "bathroom",
    name: "Bathroom",
    description: "Toiletries and bathroom essentials",
    tag: "Bathroom",
    cards: [
      { character: "牙刷",  pinyin: "yáshuā",    meaning: "toothbrush" },
      { character: "牙膏",  pinyin: "yágāo",     meaning: "toothpaste" },
      { character: "肥皂",  pinyin: "féizào",    meaning: "soap (bar)" },
      { character: "洗发水",pinyin: "xǐfàshuǐ",  meaning: "shampoo" },
      { character: "毛巾",  pinyin: "máojīn",    meaning: "towel" },
      { character: "淋浴",  pinyin: "línyù",     meaning: "shower" },
      { character: "洗澡",  pinyin: "xǐzǎo",     meaning: "take a bath / bathe" },
      { character: "镜子",  pinyin: "jìngzi",    meaning: "mirror" },
      { character: "马桶",  pinyin: "mǎtǒng",    meaning: "toilet" },
      { character: "水龙头",pinyin: "shuǐlóngtóu",meaning: "tap / faucet" },
      { character: "吹风机",pinyin: "chuīfēngjī", meaning: "hair dryer" },
      { character: "剃须刀",pinyin: "tìxūdāo",   meaning: "razor / electric shaver" },
      { character: "梳子",  pinyin: "shūzi",     meaning: "comb" },
      { character: "润肤露",pinyin: "rùnfūlù",   meaning: "moisturiser / lotion" },
      { character: "香水",  pinyin: "xiāngshuǐ", meaning: "perfume / cologne" },
      { character: "棉签",  pinyin: "miánqiān",  meaning: "cotton swab / cotton bud" },
      { character: "指甲刀",pinyin: "zhǐjiǎdāo", meaning: "nail clipper" },
      { character: "体重秤",pinyin: "tǐzhòngchèng", meaning: "bathroom scale" },
      { character: "卫生纸",pinyin: "wèishēngzhǐ",  meaning: "toilet paper" },
      { character: "浴袍",  pinyin: "yùpáo",     meaning: "bathrobe" },
    ]
  },

  // ── HSK 3 ──────────────────────────────────────────────────────────────
  {
    id: "hsk3",
    name: "HSK 3",
    description: "150 intermediate words — conversations & daily life",
    tag: "HSK 3",
    cards: [
      { character: "安静",   pinyin: "ānjìng",     meaning: "quiet / peaceful" },
      { character: "把",     pinyin: "bǎ",         meaning: "(disposal marker / handle)" },
      { character: "搬",     pinyin: "bān",        meaning: "move (house) / carry" },
      { character: "被",     pinyin: "bèi",        meaning: "(passive marker)" },
      { character: "比较",   pinyin: "bǐjiào",     meaning: "compare / relatively" },
      { character: "变化",   pinyin: "biànhuà",    meaning: "change / variation" },
      { character: "别人",   pinyin: "biérén",     meaning: "other people / others" },
      { character: "比赛",   pinyin: "bǐsài",      meaning: "competition / match" },
      { character: "成绩",   pinyin: "chéngjì",    meaning: "score / grade / achievement" },
      { character: "出现",   pinyin: "chūxiàn",    meaning: "appear / emerge" },
      { character: "聪明",   pinyin: "cōngming",   meaning: "clever / smart" },
      { character: "参加",   pinyin: "cānjiā",     meaning: "join / participate / attend" },
      { character: "打算",   pinyin: "dǎsuàn",     meaning: "plan / intend" },
      { character: "担心",   pinyin: "dānxīn",     meaning: "worry / be concerned" },
      { character: "当然",   pinyin: "dāngrán",    meaning: "of course / naturally" },
      { character: "地址",   pinyin: "dìzhǐ",      meaning: "address" },
      { character: "电梯",   pinyin: "diàntī",     meaning: "elevator / lift" },
      { character: "放心",   pinyin: "fàngxīn",    meaning: "relax / stop worrying" },
      { character: "服务",   pinyin: "fúwù",       meaning: "service / serve" },
      { character: "感觉",   pinyin: "gǎnjué",     meaning: "feeling / sense / feel" },
      { character: "感谢",   pinyin: "gǎnxiè",     meaning: "thank / be grateful" },
      { character: "公园",   pinyin: "gōngyuán",   meaning: "park" },
      { character: "故事",   pinyin: "gùshi",      meaning: "story / tale" },
      { character: "关系",   pinyin: "guānxi",     meaning: "relationship / connection" },
      { character: "过去",   pinyin: "guòqù",      meaning: "past / the past" },
      { character: "花",     pinyin: "huā",        meaning: "flower / spend (money/time)" },
      { character: "环境",   pinyin: "huánjìng",   meaning: "environment / surroundings" },
      { character: "会议",   pinyin: "huìyì",      meaning: "meeting / conference" },
      { character: "机会",   pinyin: "jīhuì",      meaning: "opportunity / chance" },
      { character: "激动",   pinyin: "jīdòng",     meaning: "excited / emotional" },
      { character: "计划",   pinyin: "jìhuà",      meaning: "plan / project" },
      { character: "健康",   pinyin: "jiànkāng",   meaning: "healthy / health" },
      { character: "解决",   pinyin: "jiějué",     meaning: "solve / resolve" },
      { character: "借",     pinyin: "jiè",        meaning: "borrow / lend" },
      { character: "经理",   pinyin: "jīnglǐ",     meaning: "manager / director" },
      { character: "久",     pinyin: "jiǔ",        meaning: "long (time)" },
      { character: "决定",   pinyin: "juédìng",    meaning: "decide / decision" },
      { character: "可爱",   pinyin: "kě'ài",      meaning: "cute / adorable" },
      { character: "客人",   pinyin: "kèrén",      meaning: "guest / visitor" },
      { character: "空气",   pinyin: "kōngqì",     meaning: "air" },
      { character: "哭",     pinyin: "kū",         meaning: "cry / weep" },
      { character: "礼物",   pinyin: "lǐwù",       meaning: "gift / present" },
      { character: "历史",   pinyin: "lìshǐ",      meaning: "history" },
      { character: "厉害",   pinyin: "lìhai",      meaning: "impressive / fierce / serious" },
      { character: "联系",   pinyin: "liánxì",     meaning: "contact / get in touch" },
      { character: "离开",   pinyin: "líkāi",      meaning: "leave / depart" },
      { character: "满意",   pinyin: "mǎnyì",      meaning: "satisfied / pleased" },
      { character: "邻居",   pinyin: "línjū",      meaning: "neighbour" },
      { character: "努力",   pinyin: "nǔlì",       meaning: "work hard / make effort" },
      { character: "普通话", pinyin: "Pǔtōnghuà",  meaning: "Mandarin (standard Chinese)" },
      { character: "其实",   pinyin: "qíshí",      meaning: "actually / in fact" },
      { character: "其他",   pinyin: "qítā",       meaning: "other / the rest" },
      { character: "奇怪",   pinyin: "qíguài",     meaning: "strange / odd" },
      { character: "清楚",   pinyin: "qīngchǔ",    meaning: "clear / clearly" },
      { character: "热情",   pinyin: "rèqíng",     meaning: "enthusiastic / warm-hearted" },
      { character: "认为",   pinyin: "rènwéi",     meaning: "think / believe / consider" },
      { character: "上网",   pinyin: "shàng wǎng", meaning: "go online / surf the internet" },
      { character: "世界",   pinyin: "shìjiè",     meaning: "world" },
      { character: "树",     pinyin: "shù",        meaning: "tree" },
      { character: "刷牙",   pinyin: "shuā yá",    meaning: "brush teeth" },
      { character: "随便",   pinyin: "suíbiàn",    meaning: "casual / as you like / whatever" },
      { character: "态度",   pinyin: "tàidu",      meaning: "attitude" },
      { character: "讨论",   pinyin: "tǎolùn",     meaning: "discuss / discussion" },
      { character: "特别",   pinyin: "tèbié",      meaning: "special / especially" },
      { character: "提高",   pinyin: "tígāo",      meaning: "improve / raise / increase" },
      { character: "同意",   pinyin: "tóngyì",     meaning: "agree / approve" },
      { character: "完成",   pinyin: "wánchéng",   meaning: "complete / finish" },
      { character: "网站",   pinyin: "wǎngzhàn",   meaning: "website" },
      { character: "文化",   pinyin: "wénhuà",     meaning: "culture / civilization" },
      { character: "现代",   pinyin: "xiàndài",    meaning: "modern / contemporary" },
      { character: "相信",   pinyin: "xiāngxìn",   meaning: "believe / trust" },
      { character: "选择",   pinyin: "xuǎnzé",     meaning: "choose / choice" },
      { character: "要求",   pinyin: "yāoqiú",     meaning: "requirement / demand" },
      { character: "叶子",   pinyin: "yèzi",       meaning: "leaf" },
      { character: "一般",   pinyin: "yībān",      meaning: "ordinary / generally" },
      { character: "一定",   pinyin: "yīdìng",     meaning: "certainly / definitely" },
      { character: "应该",   pinyin: "yīnggāi",    meaning: "should / ought to" },
      { character: "影响",   pinyin: "yǐngxiǎng",  meaning: "influence / affect" },
      { character: "游戏",   pinyin: "yóuxì",      meaning: "game / play" },
      { character: "有名",   pinyin: "yǒumíng",    meaning: "famous / well-known" },
      { character: "月亮",   pinyin: "yuèliang",   meaning: "moon" },
      { character: "愿意",   pinyin: "yuànyì",     meaning: "willing / be willing to" },
      { character: "糟糕",   pinyin: "zāogāo",     meaning: "terrible / awful / oh no!" },
      { character: "增加",   pinyin: "zēngjiā",    meaning: "increase / add" },
      { character: "重要",   pinyin: "zhòngyào",   meaning: "important" },
      { character: "注意",   pinyin: "zhùyì",      meaning: "pay attention / notice" },
      { character: "自己",   pinyin: "zìjǐ",       meaning: "oneself / self" },
      { character: "总是",   pinyin: "zǒngshì",    meaning: "always / all the time" },
      { character: "继续",   pinyin: "jìxù",       meaning: "continue / keep on" },
      { character: "感情",   pinyin: "gǎnqíng",    meaning: "feeling / emotion / affection" },
      { character: "根据",   pinyin: "gēnjù",      meaning: "according to / based on" },
      { character: "节日",   pinyin: "jiérì",      meaning: "holiday / festival" },
      { character: "举行",   pinyin: "jǔxíng",     meaning: "hold (an event) / take place" },
      { character: "经济",   pinyin: "jīngjì",     meaning: "economy / economic" },
      { character: "简单",   pinyin: "jiǎndān",    meaning: "simple / easy" },
      { character: "感冒",   pinyin: "gǎnmào",     meaning: "cold (illness) / catch a cold" },
      { character: "发烧",   pinyin: "fā shāo",    meaning: "have a fever" },
      { character: "超市",   pinyin: "chāoshì",    meaning: "supermarket" },
      { character: "打扫",   pinyin: "dǎsǎo",      meaning: "clean / sweep" },
      { character: "发展",   pinyin: "fāzhǎn",     meaning: "develop / development" },
      { character: "方法",   pinyin: "fāngfǎ",     meaning: "method / way" },
      { character: "请假",   pinyin: "qǐng jià",   meaning: "ask for leave" },
      { character: "年级",   pinyin: "niánjí",     meaning: "grade / year (in school)" },
      { character: "爬山",   pinyin: "pá shān",    meaning: "climb a mountain / hike" },
      { character: "皮肤",   pinyin: "pífū",       meaning: "skin" },
      { character: "明显",   pinyin: "míngxiǎn",   meaning: "obvious / evident / clear" },
      { character: "目的",   pinyin: "mùdì",       meaning: "purpose / goal / aim" },
      { character: "来不及", pinyin: "lái bù jí",  meaning: "not have enough time / too late" },
      { character: "连",     pinyin: "lián",       meaning: "even / link / connect" },
      { character: "正常",   pinyin: "zhèngcháng", meaning: "normal / regular" },
      { character: "祝贺",   pinyin: "zhùhè",      meaning: "congratulate" },
      { character: "作用",   pinyin: "zuòyòng",    meaning: "function / role / effect" },
      { character: "包括",   pinyin: "bāokuò",     meaning: "include / consist of" },
      { character: "专业",   pinyin: "zhuānyè",    meaning: "major / speciality / professional" },
      { character: "表演",   pinyin: "biǎoyǎn",    meaning: "perform / performance" },
      { character: "层",     pinyin: "céng",       meaning: "floor / layer / storey" },
      { character: "差不多", pinyin: "chàbuduō",   meaning: "almost / about the same" },
      { character: "成功",   pinyin: "chénggōng",  meaning: "succeed / success" },
      { character: "打折",   pinyin: "dǎzhé",      meaning: "give a discount" },
      { character: "导游",   pinyin: "dǎoyóu",     meaning: "tour guide" },
      { character: "翻译",   pinyin: "fānyì",      meaning: "translate / interpreter" },
      { character: "风景",   pinyin: "fēngjǐng",   meaning: "scenery / landscape" },
      { character: "负责",   pinyin: "fùzé",       meaning: "responsible / in charge" },
      { character: "合适",   pinyin: "héshì",      meaning: "suitable / appropriate" },
      { character: "护士",   pinyin: "hùshi",      meaning: "nurse" },
      { character: "回忆",   pinyin: "huíyì",      meaning: "recall / recollect" },
      { character: "活动",   pinyin: "huódòng",    meaning: "activity / event / exercise" },
      { character: "坚持",   pinyin: "jiānchí",    meaning: "persist / keep up / insist" },
      { character: "建议",   pinyin: "jiànyì",     meaning: "suggest / advice" },
      { character: "精彩",   pinyin: "jīngcǎi",    meaning: "wonderful / brilliant" },
      { character: "了解",   pinyin: "liǎojiě",    meaning: "understand / learn about" },
      { character: "开始",   pinyin: "kāishǐ",     meaning: "begin / start" },
      { character: "渐渐",   pinyin: "jiànjiàn",   meaning: "gradually / little by little" },
      { character: "时间",   pinyin: "shíjiān",    meaning: "time / period of time" },
      { character: "有意思", pinyin: "yǒu yìsi",   meaning: "interesting / fun" },
      { character: "举",     pinyin: "jǔ",         meaning: "raise / lift / hold up" },
      { character: "照顾",   pinyin: "zhàogù",     meaning: "take care of / look after" },
      { character: "数量",   pinyin: "shùliàng",   meaning: "quantity / amount / number" },
      { character: "伤心",   pinyin: "shāngxīn",   meaning: "sad / heartbroken" },
      { character: "已经",   pinyin: "yǐjīng",     meaning: "already" },
      { character: "停",     pinyin: "tíng",       meaning: "stop / halt / park" },
      { character: "经过",   pinyin: "jīngguò",    meaning: "pass by / go through / after" },
      { character: "提",     pinyin: "tí",         meaning: "carry / raise / bring up" },
      { character: "交",     pinyin: "jiāo",       meaning: "hand in / submit / pay / make friends" },
      { character: "关",     pinyin: "guān",       meaning: "close / shut / turn off" },
    ]
  },

  // ── HSK 4 ──────────────────────────────────────────────────────────────
  {
    id: "hsk4",
    name: "HSK 4",
    description: "150 upper-intermediate words — formal & professional life",
    tag: "HSK 4",
    cards: [
      { character: "爱好",   pinyin: "àihào",      meaning: "hobby / interest" },
      { character: "按照",   pinyin: "ànzhào",     meaning: "according to / in accordance with" },
      { character: "本来",   pinyin: "běnlái",     meaning: "originally / at first" },
      { character: "必须",   pinyin: "bìxū",       meaning: "must / have to" },
      { character: "表达",   pinyin: "biǎodá",     meaning: "express / convey" },
      { character: "部分",   pinyin: "bùfen",      meaning: "part / portion" },
      { character: "重视",   pinyin: "zhòngshì",   meaning: "attach importance to / value" },
      { character: "传统",   pinyin: "chuántǒng",  meaning: "traditional / tradition" },
      { character: "从来",   pinyin: "cónglái",    meaning: "always / (in negatives: never)" },
      { character: "大概",   pinyin: "dàgài",      meaning: "probably / approximately" },
      { character: "当时",   pinyin: "dāngshí",    meaning: "at that time / then" },
      { character: "道理",   pinyin: "dàolǐ",      meaning: "reason / sense / principle" },
      { character: "地球",   pinyin: "dìqiú",      meaning: "Earth / the globe" },
      { character: "独立",   pinyin: "dúlì",       meaning: "independent / independence" },
      { character: "而且",   pinyin: "érqiě",      meaning: "furthermore / moreover / and" },
      { character: "方面",   pinyin: "fāngmiàn",   meaning: "aspect / field / side" },
      { character: "分析",   pinyin: "fēnxī",      meaning: "analyze / analysis" },
      { character: "否则",   pinyin: "fǒuzé",      meaning: "otherwise / or else" },
      { character: "感激",   pinyin: "gǎnjī",      meaning: "grateful / thankful" },
      { character: "各种",   pinyin: "gèzhǒng",    meaning: "various / all kinds of" },
      { character: "共同",   pinyin: "gòngtóng",   meaning: "common / together / joint" },
      { character: "鼓励",   pinyin: "gǔlì",       meaning: "encourage / encouragement" },
      { character: "故意",   pinyin: "gùyì",       meaning: "intentionally / on purpose" },
      { character: "观点",   pinyin: "guāndiǎn",   meaning: "viewpoint / perspective" },
      { character: "规定",   pinyin: "guīdìng",    meaning: "regulation / rule / stipulate" },
      { character: "国际",   pinyin: "guójì",      meaning: "international" },
      { character: "合法",   pinyin: "héfǎ",       meaning: "legal / lawful" },
      { character: "后悔",   pinyin: "hòuhuǐ",     meaning: "regret" },
      { character: "忽然",   pinyin: "hūrán",      meaning: "suddenly / all of a sudden" },
      { character: "互相",   pinyin: "hùxiāng",    meaning: "mutually / each other" },
      { character: "回答",   pinyin: "huídá",      meaning: "answer / reply" },
      { character: "记录",   pinyin: "jìlù",       meaning: "record / document" },
      { character: "技术",   pinyin: "jìshù",      meaning: "technology / technique / skill" },
      { character: "加油",   pinyin: "jiā yóu",    meaning: "cheer up / keep it up / go!" },
      { character: "价格",   pinyin: "jiàgé",      meaning: "price" },
      { character: "减少",   pinyin: "jiǎnshǎo",   meaning: "reduce / decrease" },
      { character: "将来",   pinyin: "jiānglái",   meaning: "future / in the future" },
      { character: "角度",   pinyin: "jiǎodù",     meaning: "angle / perspective" },
      { character: "教育",   pinyin: "jiàoyù",     meaning: "educate / education" },
      { character: "究竟",   pinyin: "jiūjìng",    meaning: "exactly / after all / in the end" },
      { character: "靠",     pinyin: "kào",        meaning: "lean on / rely on / near" },
      { character: "可惜",   pinyin: "kěxī",       meaning: "pity / it's a shame" },
      { character: "困难",   pinyin: "kùnnán",     meaning: "difficult / difficulty" },
      { character: "理论",   pinyin: "lǐlùn",      meaning: "theory" },
      { character: "立即",   pinyin: "lìjí",       meaning: "immediately / at once" },
      { character: "例如",   pinyin: "lìrú",       meaning: "for example / such as" },
      { character: "利用",   pinyin: "lìyòng",     meaning: "use / make use of" },
      { character: "领导",   pinyin: "lǐngdǎo",    meaning: "lead / leader" },
      { character: "目前",   pinyin: "mùqián",     meaning: "currently / at present" },
      { character: "内容",   pinyin: "nèiróng",    meaning: "content / substance" },
      { character: "能力",   pinyin: "nénglì",     meaning: "ability / capability" },
      { character: "年龄",   pinyin: "niánlíng",   meaning: "age" },
      { character: "偶尔",   pinyin: "ǒu'ěr",      meaning: "occasionally / once in a while" },
      { character: "培养",   pinyin: "péiyǎng",    meaning: "cultivate / train / develop" },
      { character: "平时",   pinyin: "píngshí",    meaning: "usually / in normal times" },
      { character: "批评",   pinyin: "pīpíng",     meaning: "criticize / criticism" },
      { character: "普遍",   pinyin: "pǔbiàn",     meaning: "universal / common / widespread" },
      { character: "情况",   pinyin: "qíngkuàng",  meaning: "situation / condition" },
      { character: "确实",   pinyin: "quèshí",     meaning: "indeed / really / truly" },
      { character: "任何",   pinyin: "rènhé",      meaning: "any / whatever" },
      { character: "认真",   pinyin: "rènzhēn",    meaning: "serious / careful / conscientious" },
      { character: "社会",   pinyin: "shèhuì",     meaning: "society" },
      { character: "实际",   pinyin: "shíjì",      meaning: "actual / practical / real" },
      { character: "实现",   pinyin: "shíxiàn",    meaning: "realize / achieve / fulfill" },
      { character: "使用",   pinyin: "shǐyòng",    meaning: "use / employ" },
      { character: "事实",   pinyin: "shìshí",     meaning: "fact / truth" },
      { character: "收入",   pinyin: "shōurù",     meaning: "income / revenue" },
      { character: "探索",   pinyin: "tànsuǒ",     meaning: "explore / probe" },
      { character: "提供",   pinyin: "tígōng",     meaning: "provide / offer / supply" },
      { character: "体验",   pinyin: "tǐyàn",      meaning: "experience / undergo" },
      { character: "条件",   pinyin: "tiáojiàn",   meaning: "condition / requirement" },
      { character: "通过",   pinyin: "tōngguò",    meaning: "pass / through / by means of" },
      { character: "突然",   pinyin: "tūrán",      meaning: "suddenly / unexpectedly" },
      { character: "完全",   pinyin: "wánquán",    meaning: "completely / fully" },
      { character: "危险",   pinyin: "wēixiǎn",    meaning: "dangerous / danger" },
      { character: "位置",   pinyin: "wèizhi",     meaning: "position / location" },
      { character: "系统",   pinyin: "xìtǒng",     meaning: "system" },
      { character: "显然",   pinyin: "xiǎnrán",    meaning: "obviously / clearly" },
      { character: "限制",   pinyin: "xiànzhì",    meaning: "limit / restriction" },
      { character: "信任",   pinyin: "xìnrèn",     meaning: "trust / confidence" },
      { character: "性格",   pinyin: "xìnggé",     meaning: "personality / character" },
      { character: "需要",   pinyin: "xūyào",      meaning: "need / require" },
      { character: "研究",   pinyin: "yánjiū",     meaning: "research / study / investigate" },
      { character: "意见",   pinyin: "yìjiàn",     meaning: "opinion / idea / objection" },
      { character: "原因",   pinyin: "yuányīn",    meaning: "reason / cause" },
      { character: "责任",   pinyin: "zérèn",      meaning: "responsibility / duty" },
      { character: "政府",   pinyin: "zhèngfǔ",    meaning: "government" },
      { character: "知识",   pinyin: "zhīshi",     meaning: "knowledge" },
      { character: "支持",   pinyin: "zhīchí",     meaning: "support / back up" },
      { character: "主要",   pinyin: "zhǔyào",     meaning: "main / major / primary" },
      { character: "表情",   pinyin: "biǎoqíng",   meaning: "expression / facial expression" },
      { character: "此外",   pinyin: "cǐwài",      meaning: "in addition / besides / moreover" },
      { character: "代表",   pinyin: "dàibiǎo",    meaning: "represent / delegate / representative" },
      { character: "方式",   pinyin: "fāngshì",    meaning: "method / mode / way" },
      { character: "积极",   pinyin: "jījí",       meaning: "active / positive / enthusiastic" },
      { character: "看法",   pinyin: "kànfǎ",      meaning: "view / opinion" },
      { character: "理解",   pinyin: "lǐjiě",      meaning: "understand / comprehend" },
      { character: "全部",   pinyin: "quánbù",     meaning: "all / entire / whole" },
      { character: "软件",   pinyin: "ruǎnjiàn",   meaning: "software" },
      { character: "特点",   pinyin: "tèdiǎn",     meaning: "characteristic / feature" },
      { character: "习惯",   pinyin: "xíguàn",     meaning: "habit / be used to" },
      { character: "现象",   pinyin: "xiànxiàng",  meaning: "phenomenon" },
      { character: "有效",   pinyin: "yǒuxiào",    meaning: "effective / valid" },
      { character: "印象",   pinyin: "yìnxiàng",   meaning: "impression" },
      { character: "证明",   pinyin: "zhèngmíng",  meaning: "prove / proof / certificate" },
      { character: "职业",   pinyin: "zhíyè",      meaning: "occupation / profession / career" },
      { character: "最终",   pinyin: "zuìzhōng",   meaning: "final / ultimately / in the end" },
      { character: "关键",   pinyin: "guānjiàn",   meaning: "key / crucial / vital" },
      { character: "重点",   pinyin: "zhòngdiǎn",  meaning: "key point / emphasis" },
      { character: "多余",   pinyin: "duōyú",      meaning: "surplus / extra / unnecessary" },
      { character: "发达",   pinyin: "fādá",       meaning: "developed / advanced" },
      { character: "高科技", pinyin: "gāo kējì",   meaning: "high technology / hi-tech" },
      { character: "促进",   pinyin: "cùjìn",      meaning: "promote / advance / encourage" },
      { character: "逻辑",   pinyin: "luójí",      meaning: "logic" },
      { character: "评论",   pinyin: "pínglùn",    meaning: "comment / commentary / review" },
      { character: "气氛",   pinyin: "qìfēn",      meaning: "atmosphere / ambiance" },
      { character: "期望",   pinyin: "qīwàng",     meaning: "expect / hope / expectation" },
      { character: "热烈",   pinyin: "rèliè",      meaning: "warm / enthusiastic (applause)" },
      { character: "弱点",   pinyin: "ruòdiǎn",    meaning: "weakness / weak point" },
      { character: "启发",   pinyin: "qǐfā",       meaning: "inspire / enlighten" },
      { character: "强调",   pinyin: "qiángdiào",  meaning: "emphasize / stress" },
      { character: "全面",   pinyin: "quánmiàn",   meaning: "comprehensive / overall" },
      { character: "热门",   pinyin: "rèmén",      meaning: "popular / hot topic" },
      { character: "人才",   pinyin: "réncái",     meaning: "talent / capable person" },
      { character: "市场",   pinyin: "shìchǎng",   meaning: "market" },
      { character: "手段",   pinyin: "shǒuduàn",   meaning: "means / method / measure" },
      { character: "依靠",   pinyin: "yīkào",      meaning: "rely on / depend on" },
      { character: "增长",   pinyin: "zēngzhǎng",  meaning: "grow / increase / growth" },
      { character: "竞争",   pinyin: "jìngzhēng",  meaning: "compete / competition" },
      { character: "价值",   pinyin: "jiàzhí",     meaning: "value / worth" },
      { character: "消费",   pinyin: "xiāofèi",    meaning: "consume / consumption" },
    ]
  },

  // ── HSK 5 ──────────────────────────────────────────────────────────────
  {
    id: "hsk5",
    name: "HSK 5",
    description: "150 advanced words — academic, abstract & nuanced",
    tag: "HSK 5",
    cards: [
      { character: "摆脱",   pinyin: "bǎituō",     meaning: "get rid of / free oneself from" },
      { character: "把握",   pinyin: "bǎwò",       meaning: "grasp / seize / confidence" },
      { character: "本质",   pinyin: "běnzhì",     meaning: "essence / nature / intrinsic" },
      { character: "必要",   pinyin: "bìyào",      meaning: "necessary / essential" },
      { character: "补充",   pinyin: "bǔchōng",    meaning: "supplement / add / replenish" },
      { character: "不仅",   pinyin: "bùjǐn",      meaning: "not only" },
      { character: "财富",   pinyin: "cáifù",      meaning: "wealth / fortune" },
      { character: "策略",   pinyin: "cèlüè",      meaning: "strategy / tactics" },
      { character: "差距",   pinyin: "chājù",      meaning: "gap / disparity / difference" },
      { character: "彻底",   pinyin: "chèdǐ",      meaning: "thorough / completely / radical" },
      { character: "诚实",   pinyin: "chéngshí",   meaning: "honest / truthful" },
      { character: "冲突",   pinyin: "chōngtū",    meaning: "conflict / clash" },
      { character: "创造",   pinyin: "chuàngzào",  meaning: "create / invent" },
      { character: "充分",   pinyin: "chōngfèn",   meaning: "sufficient / full / ample" },
      { character: "词汇",   pinyin: "cíhuì",      meaning: "vocabulary / word list" },
      { character: "存在",   pinyin: "cúnzài",     meaning: "exist / existence" },
      { character: "答案",   pinyin: "dá'àn",      meaning: "answer / solution" },
      { character: "代价",   pinyin: "dàijià",     meaning: "price / cost (sacrifice)" },
      { character: "当代",   pinyin: "dāngdài",    meaning: "contemporary / present age" },
      { character: "道德",   pinyin: "dàodé",      meaning: "morality / ethics / moral" },
      { character: "地位",   pinyin: "dìwèi",      meaning: "status / position / standing" },
      { character: "调节",   pinyin: "tiáojié",    meaning: "adjust / regulate" },
      { character: "法规",   pinyin: "fǎguī",      meaning: "laws and regulations" },
      { character: "繁荣",   pinyin: "fánróng",    meaning: "prosperous / flourishing" },
      { character: "反对",   pinyin: "fǎnduì",     meaning: "oppose / object / be against" },
      { character: "范围",   pinyin: "fànwéi",     meaning: "scope / range / extent" },
      { character: "风俗",   pinyin: "fēngsú",     meaning: "custom / tradition / practice" },
      { character: "改革",   pinyin: "gǎigé",      meaning: "reform / transformation" },
      { character: "概念",   pinyin: "gàiniàn",    meaning: "concept / notion" },
      { character: "高度",   pinyin: "gāodù",      meaning: "height / highly / altitude" },
      { character: "告别",   pinyin: "gàobié",     meaning: "say goodbye / bid farewell" },
      { character: "根本",   pinyin: "gēnběn",     meaning: "fundamental / basic / at all" },
      { character: "功能",   pinyin: "gōngnéng",   meaning: "function / capability" },
      { character: "关注",   pinyin: "guānzhù",    meaning: "follow / pay close attention to" },
      { character: "广泛",   pinyin: "guǎngfàn",   meaning: "extensive / widespread / wide" },
      { character: "过程",   pinyin: "guòchéng",   meaning: "process / course" },
      { character: "合理",   pinyin: "hélǐ",       meaning: "reasonable / rational" },
      { character: "核心",   pinyin: "héxīn",      meaning: "core / nucleus / kernel" },
      { character: "互动",   pinyin: "hùdòng",     meaning: "interaction / interact" },
      { character: "幻想",   pinyin: "huànxiǎng",  meaning: "fantasy / illusion / dream" },
      { character: "活跃",   pinyin: "huóyuè",     meaning: "active / dynamic / lively" },
      { character: "获得",   pinyin: "huòdé",      meaning: "obtain / gain / win" },
      { character: "机器",   pinyin: "jīqì",       meaning: "machine / machinery" },
      { character: "积累",   pinyin: "jīlěi",      meaning: "accumulate / build up" },
      { character: "加快",   pinyin: "jiākuài",    meaning: "speed up / accelerate" },
      { character: "加强",   pinyin: "jiāqiáng",   meaning: "strengthen / intensify" },
      { character: "建设",   pinyin: "jiànshè",    meaning: "build / construct / development" },
      { character: "交流",   pinyin: "jiāoliú",    meaning: "exchange / communicate" },
      { character: "结合",   pinyin: "jiéhé",      meaning: "combine / integrate / link" },
      { character: "解释",   pinyin: "jiěshì",     meaning: "explain / interpretation" },
      { character: "进步",   pinyin: "jìnbù",      meaning: "progress / advance / improvement" },
      { character: "精神",   pinyin: "jīngshén",   meaning: "spirit / mind / essence" },
      { character: "就是",   pinyin: "jiùshì",     meaning: "just / exactly / it is / even if" },
      { character: "具有",   pinyin: "jùyǒu",      meaning: "have / possess" },
      { character: "绝对",   pinyin: "juéduì",     meaning: "absolute / absolutely" },
      { character: "可靠",   pinyin: "kěkào",      meaning: "reliable / dependable" },
      { character: "克服",   pinyin: "kèfú",       meaning: "overcome / conquer" },
      { character: "宽容",   pinyin: "kuānróng",   meaning: "tolerant / lenient" },
      { character: "困惑",   pinyin: "kùnhuò",     meaning: "confused / puzzled / bewildered" },
      { character: "理念",   pinyin: "lǐniàn",     meaning: "idea / concept / philosophy" },
      { character: "良好",   pinyin: "liánghǎo",   meaning: "good / well / fine" },
      { character: "了不起", pinyin: "liǎobuqǐ",   meaning: "amazing / extraordinary" },
      { character: "领域",   pinyin: "lǐngyù",     meaning: "field / domain / area" },
      { character: "流行",   pinyin: "liúxíng",    meaning: "popular / fashionable / prevalent" },
      { character: "描述",   pinyin: "miáoshù",    meaning: "describe / description" },
      { character: "命运",   pinyin: "mìngyùn",    meaning: "fate / destiny" },
      { character: "明确",   pinyin: "míngquè",    meaning: "clear / definite / explicit" },
      { character: "目标",   pinyin: "mùbiāo",     meaning: "goal / target / objective" },
      { character: "内心",   pinyin: "nèixīn",     meaning: "inner heart / innermost feelings" },
      { character: "平等",   pinyin: "píngděng",   meaning: "equal / equality" },
      { character: "平衡",   pinyin: "pínghéng",   meaning: "balance / equilibrium" },
      { character: "情感",   pinyin: "qínggǎn",    meaning: "emotion / feelings" },
      { character: "人才",   pinyin: "réncái",     meaning: "talent / capable person" },
      { character: "融合",   pinyin: "rónghé",     meaning: "merge / blend / integrate" },
      { character: "深刻",   pinyin: "shēnkè",     meaning: "profound / deep / insightful" },
      { character: "生产",   pinyin: "shēngchǎn",  meaning: "produce / production" },
      { character: "事业",   pinyin: "shìyè",      meaning: "career / cause / undertaking" },
      { character: "适应",   pinyin: "shìyìng",    meaning: "adapt / adjust / suit" },
      { character: "释放",   pinyin: "shìfàng",    meaning: "release / set free" },
      { character: "素质",   pinyin: "sùzhì",      meaning: "quality / character / diathesis" },
      { character: "特征",   pinyin: "tèzhēng",    meaning: "characteristic / feature" },
      { character: "体现",   pinyin: "tǐxiàn",     meaning: "embody / reflect / manifest" },
      { character: "团结",   pinyin: "tuánjié",    meaning: "unite / solidarity" },
      { character: "完善",   pinyin: "wánshàn",    meaning: "perfect / improve / complete" },
      { character: "维护",   pinyin: "wéihù",      meaning: "maintain / defend / safeguard" },
      { character: "稳定",   pinyin: "wěndìng",    meaning: "stable / steady / stabilize" },
      { character: "吸引",   pinyin: "xīyǐn",      meaning: "attract / fascinate" },
      { character: "现实",   pinyin: "xiànshí",    meaning: "reality / real / practical" },
      { character: "想象",   pinyin: "xiǎngxiàng", meaning: "imagine / imagination" },
      { character: "消失",   pinyin: "xiāoshī",    meaning: "disappear / vanish" },
      { character: "效率",   pinyin: "xiàolǜ",     meaning: "efficiency / effectiveness" },
      { character: "信念",   pinyin: "xìnniàn",    meaning: "belief / conviction / faith" },
      { character: "行为",   pinyin: "xíngwéi",    meaning: "behavior / conduct / action" },
      { character: "需求",   pinyin: "xūqiú",      meaning: "demand / need / requirement" },
      { character: "寻找",   pinyin: "xúnzhǎo",    meaning: "look for / seek / search for" },
      { character: "一致",   pinyin: "yīzhì",      meaning: "unanimous / consistent" },
      { character: "意识",   pinyin: "yìshí",      meaning: "consciousness / awareness" },
      { character: "永远",   pinyin: "yǒngyuǎn",   meaning: "forever / always / permanent" },
      { character: "勇气",   pinyin: "yǒngqì",     meaning: "courage / bravery" },
      { character: "优势",   pinyin: "yōushì",     meaning: "advantage / superiority" },
      { character: "预测",   pinyin: "yùcè",       meaning: "predict / forecast" },
      { character: "约束",   pinyin: "yuēshù",     meaning: "restrict / constrain / bind" },
      { character: "转变",   pinyin: "zhuǎnbiàn",  meaning: "transform / change / shift" },
      { character: "逐渐",   pinyin: "zhújiàn",    meaning: "gradually / step by step" },
      { character: "坚强",   pinyin: "jiānqiáng",  meaning: "strong / firm / unyielding" },
      { character: "日益",   pinyin: "rìyì",       meaning: "increasingly / day by day" },
      { character: "立即",   pinyin: "lìjí",       meaning: "immediately / at once" },
      { character: "自觉",   pinyin: "zìjué",      meaning: "conscious / aware / voluntary" },
      { character: "综合",   pinyin: "zōnghé",     meaning: "comprehensive / synthesize" },
      { character: "尊重",   pinyin: "zūnzhòng",   meaning: "respect / esteem / honor" },
      { character: "追求",   pinyin: "zhuīqiú",    meaning: "pursue / seek / strive for" },
      { character: "卓越",   pinyin: "zhuóyuè",    meaning: "outstanding / excellent" },
      { character: "力量",   pinyin: "lìliang",    meaning: "strength / power / force" },
      { character: "弥补",   pinyin: "míbǔ",       meaning: "make up for / compensate / remedy" },
      { character: "普及",   pinyin: "pǔjí",       meaning: "popularize / universalize / spread" },
      { character: "权威",   pinyin: "quánwēi",    meaning: "authority / authoritative" },
      { character: "认可",   pinyin: "rènkě",      meaning: "recognize / approve / acknowledge" },
      { character: "思考",   pinyin: "sīkǎo",      meaning: "think about / consider / ponder" },
      { character: "突破",   pinyin: "tūpò",       meaning: "breakthrough / break through" },
      { character: "压力",   pinyin: "yālì",       meaning: "pressure / stress" },
      { character: "语境",   pinyin: "yǔjìng",     meaning: "context / language environment" },
      { character: "转化",   pinyin: "zhuǎnhuà",   meaning: "transform / convert / change into" },
      { character: "深远",   pinyin: "shēnyuǎn",   meaning: "profound / far-reaching" },
      { character: "正面",   pinyin: "zhèngmiàn",  meaning: "positive / frontal / the front" },
      { character: "于是",   pinyin: "yúshì",      meaning: "therefore / so / as a result" },
      { character: "用途",   pinyin: "yòngtú",     meaning: "use / application / purpose" },
      { character: "相互",   pinyin: "xiānghù",    meaning: "mutual / each other / reciprocal" },
      { character: "思维",   pinyin: "sīwéi",      meaning: "thinking / thought / mindset" },
      { character: "衰退",   pinyin: "shuāituì",   meaning: "decline / recession / deteriorate" },
      { character: "批准",   pinyin: "pīzhǔn",     meaning: "approve / ratify / sanction" },
      { character: "气氛",   pinyin: "qìfēn",      meaning: "atmosphere / ambiance" },
      { character: "朝向",   pinyin: "cháoxiàng",  meaning: "face toward / in the direction of" },
      { character: "面临",   pinyin: "miànlín",    meaning: "face / confront / be faced with" },
      { character: "克制",   pinyin: "kèzhì",      meaning: "restrain / control oneself" },
      { character: "期间",   pinyin: "qījiān",     meaning: "period / during / time span" },
      { character: "开展",   pinyin: "kāizhǎn",    meaning: "launch / unfold / carry out" },
      { character: "极端",   pinyin: "jíduān",     meaning: "extreme / extremity / radical" },
      { character: "幸运",   pinyin: "xìngyùn",    meaning: "lucky / fortunate / good fortune" },
    ]
  },

  // ── HSK 6 ──────────────────────────────────────────────────────────────
  {
    id: "hsk6",
    name: "HSK 6",
    description: "150 high-level words — formal writing & scholarly use",
    tag: "HSK 6",
    cards: [
      { character: "摆脱",   pinyin: "bǎituō",     meaning: "get rid of / free oneself from" },
      { character: "包容",   pinyin: "bāoróng",    meaning: "tolerant / inclusive / accommodate" },
      { character: "弊端",   pinyin: "bìduān",     meaning: "disadvantage / drawback / malpractice" },
      { character: "变革",   pinyin: "biàngé",     meaning: "change / transform / reform" },
      { character: "标志",   pinyin: "biāozhì",    meaning: "sign / symbol / landmark" },
      { character: "长期",   pinyin: "chángqī",    meaning: "long-term" },
      { character: "充实",   pinyin: "chōngshí",   meaning: "enrich / substantial / rich" },
      { character: "出路",   pinyin: "chūlù",      meaning: "way out / outlet / solution" },
      { character: "创新",   pinyin: "chuàngxīn",  meaning: "innovate / innovation / creative" },
      { character: "此刻",   pinyin: "cǐkè",       meaning: "at this moment / right now" },
      { character: "促使",   pinyin: "cùshǐ",      meaning: "prompt / cause / urge" },
      { character: "带动",   pinyin: "dàidòng",    meaning: "drive / lead / spur" },
      { character: "倒退",   pinyin: "dàotuì",     meaning: "regress / retreat / go backward" },
      { character: "底线",   pinyin: "dǐxiàn",     meaning: "bottom line / baseline" },
      { character: "点燃",   pinyin: "diǎnrán",    meaning: "ignite / kindle / light" },
      { character: "对比",   pinyin: "duìbǐ",      meaning: "contrast / compare / comparison" },
      { character: "多元化", pinyin: "duōyuánhuà", meaning: "diversification / pluralization" },
      { character: "发扬",   pinyin: "fāyáng",     meaning: "carry forward / develop / promote" },
      { character: "反思",   pinyin: "fǎnsī",      meaning: "reflect on / rethink / introspect" },
      { character: "分歧",   pinyin: "fēnqí",      meaning: "divergence / difference / disagreement" },
      { character: "风险",   pinyin: "fēngxiǎn",   meaning: "risk / hazard" },
      { character: "否定",   pinyin: "fǒudìng",    meaning: "negate / deny / negative" },
      { character: "赋予",   pinyin: "fùyǔ",       meaning: "endow with / give / bestow" },
      { character: "干扰",   pinyin: "gānrǎo",     meaning: "interfere / disturb / interference" },
      { character: "更新",   pinyin: "gēngxīn",    meaning: "update / renew / upgrade" },
      { character: "共识",   pinyin: "gòngshí",    meaning: "consensus / common understanding" },
      { character: "贡献",   pinyin: "gòngxiàn",   meaning: "contribute / contribution" },
      { character: "规律",   pinyin: "guīlǜ",      meaning: "law / rule / pattern / regularity" },
      { character: "过渡",   pinyin: "guòdù",      meaning: "transition / transitional" },
      { character: "含义",   pinyin: "hányì",      meaning: "meaning / implication" },
      { character: "合并",   pinyin: "hébìng",     meaning: "merge / combine / amalgamate" },
      { character: "后果",   pinyin: "hòuguǒ",     meaning: "consequence / outcome / result" },
      { character: "化解",   pinyin: "huàjiě",     meaning: "resolve / dissolve / neutralize" },
      { character: "基础",   pinyin: "jīchǔ",      meaning: "foundation / base / basis" },
      { character: "激发",   pinyin: "jīfā",       meaning: "inspire / stimulate / arouse" },
      { character: "集中",   pinyin: "jízhōng",    meaning: "concentrate / focus / centralize" },
      { character: "几乎",   pinyin: "jīhū",       meaning: "almost / nearly / practically" },
      { character: "既然",   pinyin: "jìrán",      meaning: "since / now that / as" },
      { character: "坚守",   pinyin: "jiānshǒu",   meaning: "hold / defend / stick to" },
      { character: "兼顾",   pinyin: "jiāngù",     meaning: "give consideration to both sides" },
      { character: "减轻",   pinyin: "jiǎnqīng",   meaning: "lighten / reduce / alleviate" },
      { character: "交融",   pinyin: "jiāoróng",   meaning: "mingle / blend / fuse" },
      { character: "纠纷",   pinyin: "jiūfēn",     meaning: "dispute / conflict / controversy" },
      { character: "均衡",   pinyin: "jūnhéng",    meaning: "balanced / equilibrium" },
      { character: "可持续", pinyin: "kě chíxù",   meaning: "sustainable" },
      { character: "历来",   pinyin: "lìlái",      meaning: "all along / throughout history" },
      { character: "理性",   pinyin: "lǐxìng",     meaning: "rational / reason / rationality" },
      { character: "立足",   pinyin: "lìzú",       meaning: "stand on / base oneself on" },
      { character: "良性",   pinyin: "liángxìng",  meaning: "benign / healthy / positive" },
      { character: "论证",   pinyin: "lùnzhèng",   meaning: "demonstrate / prove / argumentation" },
      { character: "美妙",   pinyin: "měimiào",    meaning: "wonderful / beautiful / exquisite" },
      { character: "默认",   pinyin: "mòrèn",      meaning: "default / tacit approval / acquiesce" },
      { character: "内涵",   pinyin: "nèihán",     meaning: "connotation / inner meaning / depth" },
      { character: "凝聚",   pinyin: "níngjù",     meaning: "condense / unite / converge" },
      { character: "扭转",   pinyin: "niǔzhuǎn",   meaning: "reverse / turn around / rectify" },
      { character: "排除",   pinyin: "páichú",     meaning: "exclude / eliminate / rule out" },
      { character: "评估",   pinyin: "pínggū",     meaning: "evaluate / assess / appraise" },
      { character: "破解",   pinyin: "pòjiě",      meaning: "crack / decode / break through" },
      { character: "契机",   pinyin: "qìjī",       meaning: "opportunity / turning point" },
      { character: "前景",   pinyin: "qiánjǐng",   meaning: "prospects / outlook / future" },
      { character: "强化",   pinyin: "qiánghuà",   meaning: "strengthen / intensify / reinforce" },
      { character: "确立",   pinyin: "quèlì",      meaning: "establish / affirm / set up" },
      { character: "容忍",   pinyin: "róngrěn",    meaning: "tolerate / endure / bear" },
      { character: "融入",   pinyin: "róngrù",     meaning: "blend into / integrate into" },
      { character: "深化",   pinyin: "shēnhuà",    meaning: "deepen / intensify" },
      { character: "生机",   pinyin: "shēngjī",    meaning: "vitality / life / vibrancy" },
      { character: "实施",   pinyin: "shíshī",     meaning: "implement / carry out / enforce" },
      { character: "世代",   pinyin: "shìdài",     meaning: "generation / era / age" },
      { character: "适度",   pinyin: "shìdù",      meaning: "moderate / appropriate degree" },
      { character: "随之",   pinyin: "suízhī",     meaning: "accordingly / following which" },
      { character: "坦然",   pinyin: "tǎnrán",     meaning: "calm / unperturbed / at ease" },
      { character: "体系",   pinyin: "tǐxì",       meaning: "system / structure / framework" },
      { character: "调和",   pinyin: "tiáohé",     meaning: "mediate / harmonize / reconcile" },
      { character: "统一",   pinyin: "tǒngyī",     meaning: "unify / uniform / unity" },
      { character: "透彻",   pinyin: "tòuchè",     meaning: "thorough / penetrating / insightful" },
      { character: "推进",   pinyin: "tuījìn",     meaning: "push forward / advance / promote" },
      { character: "妥协",   pinyin: "tuǒxié",     meaning: "compromise / make concessions" },
      { character: "完整",   pinyin: "wánzhěng",   meaning: "complete / intact / whole" },
      { character: "维系",   pinyin: "wéixì",      meaning: "maintain / hold together" },
      { character: "无比",   pinyin: "wúbǐ",       meaning: "incomparable / unparalleled" },
      { character: "先进",   pinyin: "xiānjìn",    meaning: "advanced / forward / progressive" },
      { character: "协调",   pinyin: "xiétiáo",    meaning: "coordinate / harmonize / balance" },
      { character: "心态",   pinyin: "xīntài",     meaning: "mental state / mindset / attitude" },
      { character: "新兴",   pinyin: "xīnxīng",    meaning: "new / rising / emerging" },
      { character: "循环",   pinyin: "xúnhuán",    meaning: "cycle / circulation / recycle" },
      { character: "异议",   pinyin: "yìyì",       meaning: "objection / dissent" },
      { character: "源于",   pinyin: "yuányú",     meaning: "originate from / stem from" },
      { character: "蕴含",   pinyin: "yùnhán",     meaning: "contain / embody / imply" },
      { character: "在于",   pinyin: "zàiyú",      meaning: "lie in / consist in / depend on" },
      { character: "长远",   pinyin: "chángyuǎn",  meaning: "long-term / far-sighted" },
      { character: "针对",   pinyin: "zhēnduì",    meaning: "aim at / in response to / target" },
      { character: "振兴",   pinyin: "zhènxīng",   meaning: "revitalize / invigorate / rejuvenate" },
      { character: "整体",   pinyin: "zhěngtǐ",    meaning: "whole / overall / entirety" },
      { character: "制度",   pinyin: "zhìdù",      meaning: "system / institution / rules" },
      { character: "注重",   pinyin: "zhùzhòng",   meaning: "emphasize / pay attention to / stress" },
      { character: "转型",   pinyin: "zhuǎnxíng",  meaning: "transform / transition / restructure" },
      { character: "阻碍",   pinyin: "zǔ'ài",      meaning: "obstruct / hinder / impediment" },
      { character: "至关重要",pinyin: "zhìguān zhòngyào", meaning: "of vital importance / critical" },
      { character: "政策",   pinyin: "zhèngcè",    meaning: "policy" },
      { character: "改善",   pinyin: "gǎishàn",    meaning: "improve / ameliorate / make better" },
      { character: "经历",   pinyin: "jīnglì",     meaning: "experience / go through" },
      { character: "明朗",   pinyin: "mínglǎng",   meaning: "clear / bright / promising" },
      { character: "凝练",   pinyin: "níngliàn",   meaning: "concise / refined / polished" },
      { character: "相辅相成",pinyin: "xiāng fǔ xiāng chéng", meaning: "complement each other" },
      { character: "举足轻重",pinyin: "jǔ zú qīng zhòng",    meaning: "of great importance / decisive" },
      { character: "理所当然",pinyin: "lǐ suǒ dāngrán",      meaning: "take for granted / naturally" },
      { character: "当务之急",pinyin: "dāng wù zhī jí",      meaning: "top priority / most urgent task" },
      { character: "本末倒置",pinyin: "běn mò dào zhì",      meaning: "put the cart before the horse" },
      { character: "兴利除弊",pinyin: "xīng lì chú bì",      meaning: "promote benefits and eliminate harms" },
      { character: "参考",   pinyin: "cānkǎo",     meaning: "refer to / consult / reference" },
      { character: "阐明",   pinyin: "chǎnmíng",   meaning: "clarify / explain / expound" },
      { character: "传播",   pinyin: "chuánbō",    meaning: "spread / disseminate / broadcast" },
      { character: "导致",   pinyin: "dǎozhì",     meaning: "lead to / cause / result in" },
      { character: "对策",   pinyin: "duìcè",      meaning: "countermeasure / policy / strategy" },
      { character: "独特",   pinyin: "dútè",       meaning: "unique / distinctive / original" },
      { character: "持续",   pinyin: "chíxù",      meaning: "continue / sustain / ongoing" },
      { character: "超越",   pinyin: "chāoyuè",    meaning: "surpass / transcend / go beyond" },
      { character: "动荡",   pinyin: "dòngdàng",   meaning: "turbulence / upheaval / unrest" },
      { character: "宏伟",   pinyin: "hóngwěi",    meaning: "grand / magnificent / imposing" },
      { character: "忽视",   pinyin: "hūshì",      meaning: "ignore / overlook / neglect" },
      { character: "缓和",   pinyin: "huǎnhé",     meaning: "ease / relax / moderate" },
      { character: "汇聚",   pinyin: "huìjù",      meaning: "converge / gather / bring together" },
      { character: "混乱",   pinyin: "hùnluàn",    meaning: "chaotic / disorder / confusion" },
      { character: "激烈",   pinyin: "jīliè",      meaning: "intense / fierce / violent" },
      { character: "困境",   pinyin: "kùnjìng",    meaning: "difficult situation / plight" },
      { character: "滥用",   pinyin: "lànyòng",    meaning: "abuse / misuse / overuse" },
      { character: "利弊",   pinyin: "lìbì",       meaning: "pros and cons / advantages and disadvantages" },
      { character: "两难",   pinyin: "liǎngnán",   meaning: "dilemma / between two difficulties" },
      { character: "灵活",   pinyin: "línghuó",    meaning: "flexible / nimble / agile" },
      { character: "国情",   pinyin: "guóqíng",    meaning: "national conditions / situation" },
      { character: "凭借",   pinyin: "píngjiè",    meaning: "by means of / relying on" },
      { character: "前提",   pinyin: "qiántí",     meaning: "premise / prerequisite" },
      { character: "强烈",   pinyin: "qiángliè",   meaning: "strong / intense / powerful" },
      { character: "深化",   pinyin: "shēnhuà",    meaning: "deepen / intensify (process)" },
      { character: "显著",   pinyin: "xiǎnzhù",    meaning: "notable / remarkable / significant" },
      { character: "相互依存",pinyin: "xiānghù yīcún", meaning: "mutual dependence / interdependence" },
      { character: "整合",   pinyin: "zhěnghé",    meaning: "integrate / consolidate / merge" },
      { character: "致力于", pinyin: "zhìlì yú",   meaning: "devote oneself to / be committed to" },
      { character: "主导",   pinyin: "zhǔdǎo",     meaning: "dominant / leading / guide" },
      { character: "自主",   pinyin: "zìzhǔ",      meaning: "autonomous / self-reliant / independent" },
    ]
  },

];
